service: myserverlessproject
provider:
  name: aws
  runtime: nodejs14.x
  profile: salim
plugins:
  - serverless-s3-sync
custom:
  tableName: player-points1
  #nom du tablo
  s3Sync:
   - bucketName: salimbucket1
     localDir: UploadData
functions:
  getUser:
    handler: lambdas/endpoints/getUser.handler
    events: 
      - http:
          path: get-user/{ID}
          method: GET
          cors: true
resources: 
    Resources:
       DemoBucketUpload:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: salimbucket1
                #tabloDynamo DB
       MyDynamoDbTable:
            Type: AWS::DynamoDB::Table
            Properties: 
              TableName: ${self:custom.tableName}
              AttributeDefinitions:
                - AttributeName: ID
                  AttributeType: S
              KeySchema:
                - AttributeName: ID
                  KeyType: HASH
              BillingMode: PAY_PER_REQUEST        